### ISSUE TITLE
Evaluation system

### ISSUE THREAD

**Issue by electron1029** [recsyschallenge/2016#37]
How long will the evaluation system be available? I know it's no longer good for the challenge, but if we would like to keep working on the problem for fun.

**Comment by electron1029** [comment]
I have still been using this... Went on today and the site xing.recsys.com just loads continuously. Is the site going to come back up?

**Comment by dkohlsdorf** [comment]
Yes, we will work on it. The submission system as well as the data will be online again in January

Daniel

**Comment by electron1029** [comment]
Is there any way you can run one file for me before then? I was using this for something for a Master's project so now I'm kinda stuck.

**Comment by fabianabel** [comment]
@sakuya3834 we can send you the solution file so that you can do your evaluations on your own machine (you would just need to implement a method that iterates over all target users and then sums up the scores as described in [EvaluationMeasure.md](https://github.com/recsyschallenge/2016/blob/master/EvaluationMeasure.md)). Just let me know your email address or XING account name so that we can send you the file.

**Comment by electron1029** [comment]
It's 
s a k u y a 3 8 3 4 at gmail dot com

without the spaces of course
